### ISSUE TITLE
对于文档的一些评论

### ISSUE THREAD

**Issue by S4Life29** [Mon1-innovation/MAICA#1]
1、建议把依赖标注清楚一些，例如在用pip跑依赖安装脚本时如果你没装MySQL会报错导致不能完全安装：，建议加入sudo apt-get install libmysqlclient-dev以解决问题。
2、后端开发文档中touch.env第45行打错了一个·符号。

**Comment by edgeinfinity1** [comment]
.env是对的
很多其它项目的pip引导也不会带上系统依赖, 我自己也是一路查过来的. 我也懒得加了, 很容易查到.
